print("My name is %s and age is %d years" %('Karthik',20))
print("The first letter of %s is %c" %('python','p'))
print("The sum = %i" %(-15))
print("%o is the octal equivalent of %d" %(25,25))
print("%X is the hexadecimal equivalent of %d" %(255,255))
print("%e is the exponential equivalent of %f" %(898354,898354))
print("I am 6’2\" tall.")
print("I am Yamuna \n My age is 19")
string="Karuppasamy K"
print(string.capitalize())
print(string.center(30,'*'))
print(string.isalnum())
print(string.isnumeric())
print(string.isalpha())
print(min(string))
print(max(string))
print(string.swapcase())
print(string.title())
